### PR TITLE
#1 Add rubocop and letter_opener gems

### PR DESCRIPTION
**Pull request by gvoicu**
Based on the discussion had here #1 , I added rubocop and letter_opener gem and also fixed the coding style based on rubocop proposals.

### CODE REVIEW

**Comment by ManuelFrigerio** [comment]
@gvoicu  Was it necessary to change the coding style and indentation of so many files?

**Comment by gvoicu** [comment]
I changed the files based on rubocop with the style we have defined there. If you think it's too much, we could change the rubocop rules based on the styling you already have in the code. Or we could remove rubocop.

What do you think?

**Comment by ManuelFrigerio** [comment]
The truth is, the styling in the Blueprint is the one I normally use. I'd rather not have to completely change the indentation and styling of everything. So if it's easy to change the rubocop, then let's go with that.

**Comment by gvoicu** [comment]
Sure! I will try to match the current style of blueprint. If not, I will remove it.

**Comment by gvoicu** [comment]
I propose to close this PR and I'll open a new one tomorrow. Are you ok with this?

**Pull request closed without merging**
